do
    foo: int = 2
    print(str(foo))
end
print(str(foo)) # error